app = "autocad-converter-2024"
primary_region = "ord"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "autocad_data"
  destination = "/app/data"

[[env]]
  FLASK_ENV = "production"
  FLASK_APP = "app.py"
  OPENAI_BASE_URL = "https://openrouter.ai/api/v1"
  OPENROUTER_MODEL = "openai/gpt-4o-mini"
  DXF_MAX_TOKENS = "16384"
